package com.adtech.reportingsystem.model;

import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

import java.time.LocalDate;

@Entity // Marks this class as a JPA entity, meaning it maps to a database table.
@Table(name = "ad_report_data") // Specifies the exact table name in your database.
@Data // A Lombok annotation that automatically generates getters, setters, toString(), equals(), and hashCode() methods. This keeps your code concise.
@NoArgsConstructor // A Lombok annotation that generates a no-argument constructor.
@AllArgsConstructor // A Lombok annotation that generates a constructor with all fields as arguments.
public class AdReportData {

    @Id // Marks the 'id' field as the primary key of the table.
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Configures the primary key to be automatically generated by the database (e.g., auto-increment for PostgreSQL).
    private Long id;

    // These fields represent the columns in your 'ad_report_data' table.
    private String mobileAppResolvedId;
    private String mobileAppName;
    private String domain;
    private String adUnitName;
    private String adUnitId;
    private String inventoryFormatName;
    private String operatingSystemVersionName;

    private LocalDate date; // Using LocalDate is good for storing dates without time.

    private Long adExchangeTotalRequests;
    private Long adExchangeResponsesServed;
    private Double adExchangeMatchRate;
    private Long adExchangeLineItemLevelImpressions;
    private Long adExchangeLineItemLevelClicks;
    private Double adExchangeLineItemLevelCtr;
    private Double averageEcpm;
    private Double payout;

    // The getters and setters below are automatically generated by Lombok's @Data annotation.
    // They are explicitly included here for clarity, but Lombok handles their creation at compile time.

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMobileAppResolvedId() {
        return mobileAppResolvedId;
    }

    public void setMobileAppResolvedId(String mobileAppResolvedId) {
        this.mobileAppResolvedId = mobileAppResolvedId;
    }

    public String getMobileAppName() {
        return mobileAppName;
    }

    public void setMobileAppName(String mobileAppName) {
        this.mobileAppName = mobileAppName;
    }

    public String getDomain() {
        return domain;
    }

    public void setDomain(String domain) {
        this.domain = domain;
    }

    public String getAdUnitName() {
        return adUnitName;
    }

    public void setAdUnitName(String adUnitName) {
        this.adUnitName = adUnitName;
    }

    public String getAdUnitId() {
        return adUnitId;
    }

    public void setAdUnitId(String adUnitId) {
        this.adUnitId = adUnitId;
    }

    public String getInventoryFormatName() {
        return inventoryFormatName;
    }

    public void setInventoryFormatName(String inventoryFormatName) {
        this.inventoryFormatName = inventoryFormatName;
    }

    public String getOperatingSystemVersionName() {
        return operatingSystemVersionName;
    }

    public void setOperatingSystemVersionName(String operatingSystemVersionName) {
        this.operatingSystemVersionName = operatingSystemVersionName;
    }

    public LocalDate getDate() {
        return date;
    }

    public void setDate(LocalDate date) {
        this.date = date;
    }

    public Long getAdExchangeTotalRequests() {
        return adExchangeTotalRequests;
    }

    public void setAdExchangeTotalRequests(Long adExchangeTotalRequests) {
        this.adExchangeTotalRequests = adExchangeTotalRequests;
    }

    public Long getAdExchangeResponsesServed() {
        return adExchangeResponsesServed;
    }

    public void setAdExchangeResponsesServed(Long adExchangeResponsesServed) {
        this.adExchangeResponsesServed = adExchangeResponsesServed;
    }

    public Double getAdExchangeMatchRate() {
        return adExchangeMatchRate;
    }

    public void setAdExchangeMatchRate(Double adExchangeMatchRate) {
        this.adExchangeMatchRate = adExchangeMatchRate;
    }

    public Long getAdExchangeLineItemLevelImpressions() {
        return adExchangeLineItemLevelImpressions;
    }

    public void setAdExchangeLineItemLevelImpressions(Long adExchangeLineItemLevelImpressions) {
        this.adExchangeLineItemLevelImpressions = adExchangeLineItemLevelImpressions;
    }

    public Long getAdExchangeLineItemLevelClicks() {
        return adExchangeLineItemLevelClicks;
    }

    public void setAdExchangeLineItemLevelClicks(Long adExchangeLineItemLevelClicks) {
        this.adExchangeLineItemLevelClicks = adExchangeLineItemLevelClicks;
    }

    public Double getAdExchangeLineItemLevelCtr() {
        return adExchangeLineItemLevelCtr;
    }

    public void setAdExchangeLineItemLevelCtr(Double adExchangeLineItemLevelCtr) {
        this.adExchangeLineItemLevelCtr = adExchangeLineItemLevelCtr;
    }

    public Double getAverageEcpm() {
        return averageEcpm;
    }

    public void setAverageEcpm(Double averageEcpm) {
        this.averageEcpm = averageEcpm;
    }

    public Double getPayout() {
        return payout;
    }

    public void setPayout(Double payout) {
        this.payout = payout;
    }
}
